@startuml

title __NUKEIT's Class Diagram__\n

  namespace nl.han.ica.oopg.alarm {
    class nl.han.ica.oopg.alarm.Alarm {
    }
  }
  

  namespace nl.han.ica.oopg.alarm {
    class nl.han.ica.oopg.alarm.AlarmTest {
    }
  }
  

  namespace nl.han.ica.oopg.alarm {
    interface nl.han.ica.oopg.alarm.IAlarmListener {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    class nl.han.ica.oopg.collision.CollidedTile {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    enum CollisionSide {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    class nl.han.ica.oopg.collision.GameObjectCollisionTest {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    interface nl.han.ica.oopg.collision.ICollidableWithGameObjects {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    interface nl.han.ica.oopg.collision.ICollidableWithTiles {
    }
  }
  

  namespace nl.han.ica.oopg.collision {
    class nl.han.ica.oopg.collision.TileCollisionTest {
    }
  }
  

  namespace nl.han.ica.oopg.dashboard {
    class nl.han.ica.oopg.dashboard.Dashboard {
    }
  }
  

  namespace nl.han.ica.oopg.dashboard {
    class nl.han.ica.oopg.dashboard.DashboardTest {
    }
  }
  

  namespace nl.han.ica.oopg.dashboard {
    class nl.han.ica.oopg.dashboard.FPSCounter {
    }
  }
  

  namespace nl.han.ica.oopg.engine {
    abstract class nl.han.ica.oopg.engine.GameEngine {
    }
  }
  

  namespace nl.han.ica.oopg.engine {
    class nl.han.ica.oopg.engine.GameEngineTest {
    }
  }
  

  namespace nl.han.ica.oopg.engine {
    class nl.han.ica.oopg.engine.GameThread {
    }
  }
  

  namespace nl.han.ica.oopg.exceptions {
    class nl.han.ica.oopg.exceptions.GameEngineRuntimeException {
    }
  }
  

  namespace nl.han.ica.oopg.exceptions {
    class nl.han.ica.oopg.exceptions.LoggerRuntimeException {
    }
  }
  

  namespace nl.han.ica.oopg.exceptions {
    class nl.han.ica.oopg.exceptions.TileNotFoundException {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    class nl.han.ica.oopg.logger.DefaultLogger {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    class nl.han.ica.oopg.logger.FileLogHandler {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    class nl.han.ica.oopg.logger.LogFactory {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    interface nl.han.ica.oopg.logger.LogHandler {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    interface nl.han.ica.oopg.logger.Logger {
    }
  }
  

  namespace nl.han.ica.oopg.logger {
    class nl.han.ica.oopg.logger.loggerTest {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    abstract class nl.han.ica.oopg.objects.AnimatedSpriteObject {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.AnimatedSpriteObjectTest {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    abstract class nl.han.ica.oopg.objects.GameObject {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.GameObjectTest {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.Sprite {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    abstract class nl.han.ica.oopg.objects.SpriteObject {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.SpriteObjectTest {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.SpriteTest {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.TextObject {
    }
  }
  

  namespace nl.han.ica.oopg.objects {
    class nl.han.ica.oopg.objects.TextObjectTest {
    }
  }
  

  namespace nl.han.ica.oopg.persistence {
    class nl.han.ica.oopg.persistence.FilePersistence {
    }
  }
  

  namespace nl.han.ica.oopg.persistence {
    class nl.han.ica.oopg.persistence.FilePersistenceTest {
    }
  }
  

  namespace nl.han.ica.oopg.persistence {
    interface nl.han.ica.oopg.persistence.IPersistence {
    }
  }
  

  namespace nl.han.ica.oopg.pgraphicsstub {
    class nl.han.ica.oopg.pgraphicsstub.PGraphicsCreatorMock {
    }
  }
  

  namespace nl.han.ica.oopg.pgraphicsstub {
    class nl.han.ica.oopg.pgraphicsstub.PGraphicsGameObject {
    }
  }
  

  namespace nl.han.ica.oopg.pgraphicsstub {
    class nl.han.ica.oopg.pgraphicsstub.PGraphicsMock {
    }
  }
  

  namespace nl.han.ica.oopg.sound {
    class nl.han.ica.oopg.sound.Sound {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.EmptyTile {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.MockTile {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.Tile {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.TileMap {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.TileMapTest {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.TileTest {
    }
  }
  

  namespace nl.han.ica.oopg.tile {
    class nl.han.ica.oopg.tile.TileType {
    }
  }
  

  namespace nl.han.ica.oopg.userinput {
    interface nl.han.ica.oopg.userinput.IKeyInput {
    }
  }
  

  namespace nl.han.ica.oopg.userinput {
    interface nl.han.ica.oopg.userinput.IMouseInput {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.CenterFollowingViewPortTest {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.CenterFollowingViewport {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.EdgeFollowingViewPortTest {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.EdgeFollowingViewport {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.FollowingViewPortTest {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    abstract class nl.han.ica.oopg.view.FollowingViewport {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.PGraphicsCreator {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.View {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.ViewPortTest {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.ViewTest {
    }
  }
  

  namespace nl.han.ica.oopg.view {
    class nl.han.ica.oopg.view.Viewport {
    }
  }
  

  namespace nl.han.oopg.nukeit.AbstractClasses {
    abstract class nl.han.oopg.nukeit.AbstractClasses.Bullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.AbstractClasses {
    abstract class nl.han.oopg.nukeit.AbstractClasses.Bullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.AbstractClasses {
    abstract class nl.han.oopg.nukeit.AbstractClasses.Spawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.AbstractClasses {
    abstract class nl.han.oopg.nukeit.AbstractClasses.Spawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Alien {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Alien {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Alien {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Alien {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AlienSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Asteroid {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Asteroid {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Asteroid {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Asteroid {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AsteroidSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AsteroidSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AsteroidSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.AsteroidSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.LifePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.LifePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.LifePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.LifePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NormalFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NormalFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NormalFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NormalFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITWorld {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITWorld {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITWorld {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.NukeITWorld {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.PowerUpSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.PowerUpSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.PowerUpSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.PowerUpSpawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.RapidFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.RapidFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.RapidFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.RapidFirePowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Ship {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Ship {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Ship {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.Ship {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.ShipBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.ShipBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.ShipBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.ShipBullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.TripleShotPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.TripleShotPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.TripleShotPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Classes {
    class nl.han.oopg.nukeit.Classes.TripleShotPowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum FireMode {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum FireMode {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum FireMode {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum FireMode {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum GameState {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum GameState {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum GameState {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum GameState {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum PowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum PowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum PowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Enums {
    enum PowerUp {
    }
  }
  

  namespace nl.han.oopg.nukeit.Interfaces {
    abstract class nl.han.oopg.nukeit.Interfaces.Bullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Interfaces {
    abstract class nl.han.oopg.nukeit.Interfaces.Bullet {
    }
  }
  

  namespace nl.han.oopg.nukeit.Interfaces {
    abstract class nl.han.oopg.nukeit.Interfaces.Spawner {
    }
  }
  

  namespace nl.han.oopg.nukeit.Interfaces {
    abstract class nl.han.oopg.nukeit.Interfaces.Spawner {
    }
  }
  

  nl.han.ica.oopg.dashboard.FPSCounter .up.|> nl.han.ica.oopg.alarm.IAlarmListener
  nl.han.ica.oopg.engine.GameThread .up.|> java.lang.Runnable
  nl.han.ica.oopg.logger.DefaultLogger .up.|> nl.han.ica.oopg.logger.Logger
  nl.han.ica.oopg.logger.FileLogHandler .up.|> nl.han.ica.oopg.logger.LogHandler
  nl.han.ica.oopg.objects.GameObject .up.|> nl.han.ica.oopg.userinput.IKeyInput
  nl.han.ica.oopg.objects.GameObject .up.|> nl.han.ica.oopg.userinput.IMouseInput
  nl.han.ica.oopg.objects.GameObject .up.|> processing.core.PConstants
  nl.han.ica.oopg.persistence.FilePersistence .up.|> nl.han.ica.oopg.persistence.IPersistence
  nl.han.oopg.nukeit.AbstractClasses.Bullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.AbstractClasses.Bullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Alien .up.|> IAlarmListener
  nl.han.oopg.nukeit.Classes.Alien .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Alien .up.|> nl.han.ica.oopg.alarm.IAlarmListener
  nl.han.oopg.nukeit.Classes.Alien .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Alien .up.|> IAlarmListener
  nl.han.oopg.nukeit.Classes.Alien .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Alien .up.|> nl.han.ica.oopg.alarm.IAlarmListener
  nl.han.oopg.nukeit.Classes.Alien .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.AlienBullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.AlienBullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.AlienBullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.AlienBullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Asteroid .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Asteroid .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Asteroid .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Asteroid .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.LifePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.LifePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.LifePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.LifePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NormalFirePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NormalFirePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NormalFirePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NormalFirePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NukeITPowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NukeITPowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NukeITPowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.NukeITPowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.RapidFirePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.RapidFirePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.RapidFirePowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.RapidFirePowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Ship .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Ship .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Ship .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.Ship .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.ShipBullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.ShipBullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.ShipBullet .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.ShipBullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.TripleShotPowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.TripleShotPowerUp .up.|> ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.TripleShotPowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Classes.TripleShotPowerUp .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Interfaces.Bullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects
  nl.han.oopg.nukeit.Interfaces.Bullet .up.|> nl.han.ica.oopg.collision.ICollidableWithGameObjects


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
